dataset:
  name: how2sign
  download: true
  manifest: true
  source:
    manifest_csv: dataset/how2sign/text/how2sign_realigned_val.csv
    split: val

processing:
  enabled: true
  processor: video2pose
  detection: "null"
  pose: mediapipe
  sample_rate: 0.5
  max_workers: 1
  pose_config:
    model_complexity: 1
    min_detection_confidence: 0.5
    min_tracking_confidence: 0.5
    refine_face_landmarks: true
    batch_size: 16

post_processing:
  enabled: true
  recipes:
    - normalize
  normalize:
    keypoint_preset: mediapipe_553_to_85
    mode: xy_isotropic_z_minmax
    mask_empty_frames: true

output:
  enabled: true
  type: webdataset

run_name: default

paths:
  root: dataset/how2sign
  videos: dataset/how2sign/videos
  manifest: dataset/how2sign/how2sign_realigned_val.csv
