dataset: how2sign
recipe: pose
run_name: default

paths:
  root: dataset/how2sign
  videos: dataset/how2sign/videos
  manifest: dataset/how2sign/how2sign_realigned_val.csv

extractor:
  name: mmpose
  bbox_threshold: 0.5
  keypoint_threshold: 0.3
  add_visible: true
  device: "cuda:0"
  pose_model_config: resources/pose_models/mmpose/configs/rtmw3d-l_8xb64_cocktail14-384x288.py
  pose_model_checkpoint: src/signdata/models/checkpoints/rtmw3d-l_8xb64_cocktail14-384x288-794dbc78_20240626.pth
  det_model_config: resources/detection_models/rtmdet/configs/rtmdet_nano_320-8xb32_coco-person.py
  det_model_checkpoint: src/signdata/models/checkpoints/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth

normalize:
  keypoint_preset: mmpose_133_to_85
  mode: xy_isotropic_z_minmax
  mask_empty_frames: true

processing:
  target_fps: 24.0
  frame_skip: 2
