dataset:
  name: how2sign
  download: true
  manifest: true
  source:
    manifest_csv: dataset/how2sign/text/how2sign_realigned_val.csv
    split: val

processing:
  enabled: true
  processor: video2crop
  detection: yolo
  sample_rate: 0.5
  max_workers: 4
  detection_config:
    model: yolo11m.pt
    device: cpu
    confidence_threshold: 0.5
    batch_size: 16
  video_config:
    codec: libx264
    padding: 0.0

post_processing:
  enabled: false

output:
  enabled: true
  type: webdataset

run_name: default

paths:
  root: dataset/how2sign
  videos: dataset/how2sign/videos
  manifest: dataset/how2sign/how2sign_realigned_val.csv
